services:
  mysql-db:
    image: mysql:8.4
    container_name: gamerspace-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PWD}
    ports:
      - "3367:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gamerspace-net

  backend-api:
    build:
      context: .
      dockerfile: Backend/GamerSpace.API/Dockerfile
    container_name: gamerspace-backend
    depends_on:
      - mysql-db
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Default: "Server=mysql-db;Port=3306;Database=${MYSQL_DB_NAME};User=${MYSQL_USER_NAME};Password=${MYSQL_USER_PWD};TreatTinyAsBoolean=true"
      Jwt__Key: ${JWT_SECRET_KEY}
      Jwt__Issuer: "GamerSpace.API"
      Jwt__Audience: "GamerSpace.Frontend"
    ports:
      - "5000:8080"
    networks:
      - gamerspace-net

  frontend-app:
    build:
      context: ./GamerSpace.UI
      dockerfile: Dockerfile
    container_name: gamerspace-frontend
    depends_on:
      - backend-api
    ports:
      - "4200:80"
    networks:
      - gamerspace-net

networks:
  gamerspace-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
